allow = ["expect", "capacity", "format", "misaligned_ptr", "oom", "unknown"]

[[rules]]
function = "metal::device::*"
allow = ["panic"]

[[rules]]
function = "prost::*"
allow = ["bounds", "overflow"]


