allow = ["expect", "capacity", "format", "misaligned_ptr", "async_resumed", "oom", "unknown"]

[[rules]]
function = "metal::device::*"
allow = ["panic"]

[[rules]]
function = "prost::*"
allow = ["bounds", "overflow"]


